task:
    name: test (FreeBSD)
    freebsd_instance:
        image_family: freebsd-12-1
    script: |
        uname -a
        swapinfo
        pwd
        printenv
        clang --version
        git --version
        pkg info
        ls -al
